name: ZipPluginLoader
main: ZipPluginLoader\Main
version: 1.2.0
api: [1.10.0,2.0.0]
load: STARTUP
author: aliuly
description: Load Zip packed plugins
website: https://github.com/Muirfield/pocketmine-plugins/tree/master/ZipPluginLoader
